version: 2.1

jobs:
  mariadb:
    machine:
      image: ubuntu-2204:2023.02.1
    steps:
      - run:
          name: Spin up MariaDB
          command: |
            docker run --name db -e MYSQL_ALLOW_EMPTY_PASSWORD=1 -p 3306:3306 -d docker.io/library/mariadb:10.3
      - run:
          name: Install dockerize
          command: |
            wget https://github.com/jwilder/dockerize/releases/download/v0.6.0/dockerize-linux-amd64-v0.6.0.tar.gz
            sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-v0.6.0.tar.gz
      - run: |
          dockerize -wait tcp://127.0.0.1:3306 -timeout 20s
      - run: |
          mysql -u root -h 127.0.0.1 -e "show databases;"
      - run: |
          mysql -u root -h 127.0.0.1 -e "CREATE DATABASE drupal;"
      - run: |
          mysql -u root -h 127.0.0.1 -e "show databases;"
 
workflows:
  main:
    jobs:
      - mariadb
